/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	__asm__ volatile (

		//enabling GPIO clock
		"movw r0, #0x104C\n\t" //lower
		"movt r0, #0x4002\n\t" //upper
		"ldr r1, [r0]\n\t"
		"orr r1, r1, #0x6\n\t"
		"str r1, [r0]\n\t"

		"movw r0, #0x0400\n\t"
		"movt r0, #0x4800\n\t"

		//moder
		"ldr r1, [r0]\n\t"
		"bic r1,r1,#0xC000\n\t" //uint32_t *gpiob_moder = (uint32_t *)(0x48000400 + 0x00);
		"orr r1, r1,#0x4000\n\t" //1UL << 14
		"str r1, [r0]\n\t"

	    //otyper
		"ldr r1, [r0, #0x04]\n\t" //uint32_t *gpiob_otyper = (uint32_t *)(0x48000400 + 0x04);
		"bic r1, r1, #0x80\n\t"  //1UL << 7
		"str r1, [r0, #0x04]\n\t"

		//ospeedr
		"ldr r1, [r0, #0x08]\n\t" //uint32_t *gpiob_ospeedr = (uint32_t *)(0x48000400 + 0x08);
		"bic r1, r1, #0xC000\n\t" //3UL << 14
		"str r1, [r0, #0x08]\n\t"

		//pupdr
		"ldr r1, [r0, #0x0C]\n\t" //uint32_t *gpiob_pupdr = (uint32_t *)(0x48000400 + 0x0C);
		"bic r1, r1, #0xC000\n\t" //3UL << 14
		"str r1, [r0, #0x0C]\n\t"

		//odr
		"ldr r1, [r0, #0x14]\n\t" //uint32_t *gpiob_odr = (uint32_t *)(0x48000400 + 0x14);
		"orr r1, r1, #0x80\n\t" //1UL << 7
		"str r1, [r0, #0x14]\n\t"
		);
	
	while (1);
}
